name: Publications Crawler

on:
  push:
    branches: [master, main]
  schedule:
    # Run every Sunday at 2:00 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  crawl-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set API environment variables from secrets
        run: |
          if [ -z "${{ secrets.API_ENDPOINT }}" ]; then
            echo "❌ Error: API_ENDPOINT secret is not set!"
            echo "Please set the API_ENDPOINT secret in your repository settings."
            exit 1
          fi

          echo "API_ENDPOINT=${{ secrets.API_ENDPOINT }}" >> $GITHUB_ENV
          echo "API_TIMEOUT=${{ secrets.API_TIMEOUT || '30' }}" >> $GITHUB_ENV
          echo "API_RETRIES=${{ secrets.API_RETRIES || '3' }}" >> $GITHUB_ENV

          echo "✅ API_ENDPOINT set: ${{ secrets.API_ENDPOINT }}"
          echo "✅ API_TIMEOUT set: ${{ secrets.API_TIMEOUT || '30' }}"
          echo "✅ API_RETRIES set: ${{ secrets.API_RETRIES || '3' }}"

      - name: Create necessary directories
        run: |
          mkdir -p logs

      - name: Run crawler
        run: |
          python main.py

      - name: Create summary
        run: |
          echo "## Crawling Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Publications crawling completed" >> $GITHUB_STEP_SUMMARY
          echo "- Data sent to API endpoint" >> $GITHUB_STEP_SUMMARY
          echo "- Log file: logs/crawler.log" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Run completed at:** $(date)" >> $GITHUB_STEP_SUMMARY
